defaults/main.yml, tasks/main.yml
I would prefer to be able to provide my own config file in the ordinary alert-manager syntax as to reduce my lock-in on this ansible role
=> Enable ability to change config file

handlers/main.yml
I'm trying to include the `cloudalchemy.alertmanager` role from our own monitoring role like this:
```
- name: Install Prometheus Alertmanager service
become: yes
include_role:
name: cloudalchemy.alertmanager
vars:
[...]
```
This results in a fatal error, at the point when running the handler that should restart the alertmanager:
```
RUNNING HANDLER [cloudalchemy.alertmanager : restart alertmanager] ******************************************************************************************************************
fatal: [monitor]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: Failed to execute operation: Interactive authentication required.\n"}
```
The service could only be restarted with sudo-privileges, which in the case of an `include_role` or `import_role` won't …
=> Make Prometheus alertmanager service restart/reload with sudo privileges

README.md
Although the variable `alertmanager_log_dir` has been removed in PR #16 to solve issue #15, it's still being mentioned in the README. This PR will remove it from the README as well.
=> Remove variable alertmanager_log_dir, as this has been removed in PR #16

README.md, defaults/main.yml
Use latest release.
Closes: https://github.com/cloudalchemy/ansible-alertmanager/issues/23
=> Update default version

.travis.yml
This is needed due to a bug with `ss` implementation in testinfra framework. More in https://github.com/philpep/testinfra/issues/293
=> Locking testinfra version

README.md, defaults/main.yml, tests/inventory, tests/playbook.yml
Including by default a receiver configuration is misleading and causes example usage from README.md to fail.
This PR moves receiver config to be used only in tests.
=> Fix default config

.gitignore, .travis.yml, CONTRIBUTING.md, README.md, defaults/main.yml, tasks/configure.yml, tasks/install.yml, tasks/main.yml, tasks/preflight.yml, templates/alertmanager.service.j2, templates/alertmanager.yml.j2, tests/playbook.yml, tests/test_default.py, tests/vars.yml
Adding:
- multiple preflight checks (resolves #5)
- variables which are compatible in name with ansible-prometheus, backwards compatibility is present (resolves #10)
- split variables in test playbook
- specify `become` on tasks level instead of playbook one
- split tasks/main.yml into multiple files
- linter check before running molecule
- use /usr/local/bin for binaries location
Removing:
- default alert route
- default alert receiver
=> Major rework

tasks/install.yml
This should prevent issues such as network timeout.
Same as in https://github.com/cloudalchemy/ansible-prometheus/pull/86
Similar to: https://github.com/cloudalchemy/ansible-node-exporter/pull/29
=> Retry when connecting to external services

tasks/install.yml
It was raising a deprecation warning
=> Fix success test done with a filter

tasks/install.yml
`run_once` will cause problems with multi-arch environments since this role will download only one binary version.
=> Quick fix to allow multi-arch environments support

templates/alertmanager.yml.j2
fix treating smtp_require_tls value as a string, which caused amtool validation to fail
=> don't treat false, true, null as strings when templating smtp configuration

tasks/install.yml
Allow playbook to run on RedHat even if SELinux is not enabled.
=> Fix failing role on non-SELinux RedHat

.travis.yml, README.md, meta/main.yml, molecule/alternative/tests/test_alternative.py, molecule/default/tests/test_default.py, tox.ini
[Ansible 2.7 was just released](https://github.com/ansible/ansible/releases/tag/v2.7.0) :tada:. This PR deprecates support for ansible 2.4 and introduces testing on ansible 2.7
Merging this will result in a [patch] version release.
=> move to ansible 2.7

README.md, defaults/main.yml, templates/alertmanager.yml.j2
Update opsgenie global configuration options to match https://prometheus.io/docs/alerting/configuration/. Current option is invalid.
=> Update opsgenie global configs

tasks/configure.yml, tasks/install.yml
Having the service creation in the install tasks means that changes to
the configuration, such as the web.external-url, are not updated with
the configuration task.  This creates a problem if configuration is
re-applied, either as a separate step, or re-run for updating values.
Moving the service creation to the configure step ensures any new or
updated values are taken into account in the service execution.
=> Move service creation from install to configure

templates/alertmanager.service.j2, templates/alertmanager.yml.j2
This'll support multi-line ansible_managed strings but will not work on ansible 1.x.
=> Add support for multi-line ansible_managed strings

tasks/install.yml
This downloads the alertmanager tarball when using this role in check mode. Otherwise, the following task, "propagate alertmanager and amtool binaries", fails due to a missing local file.
=> Download package locally during check mode

defaults/main.yml
If you use `auth_require_tls` it causes this:
```
TASK [cloudalchemy.alertmanager : copy alertmanager config] ********************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "c7cd0a8cb6995c58ecda363077ddb05886ab7942", "exit_status": 1, "msg": "failed to validate", "stderr": "amtool: error: failed to validate 1 file(s)\n\n", "stderr_lines": ["amtool: error: failed to validate 1 file(s)", ""], "stdout": "Checking '/root/.ansible/tmp/ansible-tmp-1552268526.7-265471681937283/source'  FAILED: yaml: unmarshal errors:\n  line 11: field smtp_auth_require_tls not found in type config.plain\n\n", "stdout_lines": ["Checking '/root/.ansible/tmp/ansible-tmp-1552268526.7-265471681937283/sou …
```
=> Change auth_require_tls to require_tls

README.md, defaults/main.yml, tasks/configure.yml, templates/alertmanager.yml.j2
Allows for management of alertmanager templates within ansible for usage by reciever messages/descriptions/etc.
=> support copying of alertmanager templates

molecule/alternative/molecule.yml, molecule/default/molecule.yml, molecule/latest/molecule.yml, molecule/latest/playbook.yml, tasks/install.yml, tasks/main.yml, vars/debian.yml, vars/fedora.yml, vars/redhat.yml
Fedora updated to python3, so dependencies also need to be updated.
Packages for SELinux should be the same as specified in https://github.com/cloudalchemy/ansible-node-exporter/issues/95
=> update to fedora 30 and bring in mechanism for installing SELinux deps known from ansible-prometheus

meta/main.yml, molecule/alternative/molecule.yml, molecule/default/molecule.yml, molecule/latest/molecule.yml
From now on support for debian jessie is on best-effort basis. Around 30.06.2020 it will be dropped completely.
Tested locally. I will propagate it to all repos shortly.
=> drop testing on debian jessie and add support for debian buster

tasks/main.yml, vars/redhat-8.yml
This is based on current fedora support and it won't affect already supported platforms.
=> add support for RHEL8 (without automated testing)

templates/alertmanager.service.j2
- ReadWriteDirectories needs to be set to store data
- RestrictSUIDSGID has been introduced with Systemd 242
=> Adjust systemd restrictions

templates/alertmanager.service.j2
In my setup every run on the alertmanager cluster creates changes because the order for peer and and listen-address keeps being switched around-
=> make order of cluster args deterministic

tasks/configure.yml
A template change also requires alertmanager to be reloaded.
=> Add restart handler on template change

tasks/preflight.yml
Do not fail if `alertmanager_receivers` and `alertmanager_route` are empty while using a custom configuration template.
Since `alertmanager_config_file` is configurable it makes no sense to require these 2 variables to be non-empty if `alertmanager_config_file` is not set to its default value.
=> Do not fail when using a custom config template file

tasks/install.yml
tasks: debian-based distros doesn't have /sbin/nologin, but /usr/sbin/nologin is available on RHEL family systems
Issue found during compatibility testing with dev-sec.os-hardening role.
=> Switch user login shell to /usr/sbin/nologin

tasks/configure.yml, tasks/main.yml
When combining this role with other roles in a playbook, it would seem better to apply configuration changes straight away by flushing handlers. This makes sure that if a later stage in the deployment fails, any configuration changes will still be applied.
=> Flush handlers after configuration

README.md, defaults/main.yml, molecule/alternative/playbook.yml, tasks/preflight.yml, templates/alertmanager.yml.j2
Simplify configuration handling by removing an object which doesn't have any representation in alertmanager docs.
For backwards compatibility reasons template rendering configuration will still support `alertmanager_child_routes`. This compatibility layer should be removed after a few months (after March 2020).
=> Remove alertmanager_child_routes

tasks/preflight.yml
Apply a hacky way of showing a warning from a task \[1]. This will fail tasks, but also tolerate failure, so the user should notice the failure, but role should install alertmanager nonetheless.
Deprecation warnings should be removed with 0.19.0 release and support for alertmanager 0.15.0 with them.
\[1]: https://medium.com/opsops/how-to-print-warning-from-a-task-3286ebb39f40
=> add deprecation warnings

templates/alertmanager.yml.j2
alertmanager_http_config was duplicated, thus template would fail to
copy because of verification
=> Fixed alertmanager_http_config setting failing deploy

templates/alertmanager.yml.j2
Add support for encrypting variables in the Alertmanager template file.
This is a workaround for https://github.com/ansible/ansible/issues/33067, which prevents us from using encrypted variables here.
e.g. we define the OpsGenie API keys in our `group_vars/` files
```
alertmanager_opsgenie_api_key: !vault |
$ANSIBLE_VAULT;1.1;AES256
36633533623638323566613563663833633632626439313632336563353434623664633266306365
3935346335393033313437333837356536306636666532310a363133616463643962663233613630
62363731343566356366393461656433653236653435346634396131306239363339376635366230
6537326136373436360a336439353535356436376133316239313664613434373934316265666162
63643361313935303735333961393461653161376435316332356636326230333138
```
This change, as suggested in the above mentioned issue, allows us …
=> Support encrypted variables in Alertmanager template file

tasks/preflight.yml
It looks like the var is removed, but the deprecation notice doesn't fail.
=> Fix: fail on alertmanager_child_routes

README.md, defaults/main.yml, tasks/configure.yml, tasks/install.yml, templates/amtool.yml.j2, vars/main.yml
I can rebase that on the other PR. :)
=> Add amtool configuration on alertmanager host

tasks/preflight.yml
I'm not sure why it was disabled in the first place, especially because the
get_url used to download the tarball already validates certificates by default.
=> Enforce certificate validation during release version lookup
